# Generated by Django 5.2.6 on 2025-09-08 11:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_file_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmembership',
            old_name='user',
            new_name='member',
        ),
        migrations.AlterUniqueTogether(
            name='projectmembership',
            unique_together={('project', 'member')},
        ),
    ]
