# Generated by Django 5.2.6 on 2025-09-09 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_user_projectmembership_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='updated_at',
            new_name='last_modified',
        ),
        migrations.AddField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
