# Generated by Django 5.2.6 on 2025-09-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_updated_at_file_last_modified_file_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
    ]
